name: Terraform Plan
run-name: ${{ github.actor }} created pull request from ${{ github.head_ref }} to ${{ github.base_ref }} 🧨

on: 
  pull_request:
    branches:
      - main
      
env:
  CONFIG_DIRECTORY: "./"
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  Terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform Init
        id: init
        run: terraform init
  
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color > output
          echo "run_link=$(grep '^To view this run in a browser, visit:' -A1 output | grep -v '^To view this run in a browser, visit:' | tr -d '\012\015')" >> $GITHUB_OUTPUT
          echo "plan=$(grep -E '^(Plan:|No changes.)' output | tr -d '\012\015')" >> $GITHUB_OUTPUT

      - name: Write pull request comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Run-link: ${{ steps.plan.outputs.run_link }}
            #### Something: \`${{ steps.plan.outputs.plan }}\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })