name: Terraform Run
run-name: >-
  ${{ github.event_name == 'pull_request' &&
  format('{0} created pull request from: {1} to: {2}.',
  github.actor, github.head_ref, github.base_ref) ||
  format('{0} pushed to: {1}.',
  github.actor, github.ref_name) }}

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
      
env:
  CONFIG_DIRECTORY: "./"

jobs:
  Terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    env:
      event: ${{ github.event_name }}
      branch: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Setup environment
        run: |
          if [[ $branch == "main" ]]; then
          workspace="prod"
          else
          workspace="dev"
          fi

          if [[ $event == "pull_request" ]]; then
          flag=""
          else
          flag="-out plan"
          fi
          args="$flag -var-file=./environments/$workspace/terraform.tfvars"

          echo "TF_CLI_ARGS_plan=$args" >> $GITHUB_ENV
          echo "TF_WORKSPACE=$workspace" >> $GITHUB_ENV
    
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color > output
          url=$(grep '^To view this run in a browser, visit:' -A1 output | grep -v '^To view this run in a browser, visit:' | tr -d '\012\015')
          sm=$(grep -E '^(Plan:|No changes.)' output | tr -d '\012\015')

          echo "run_link=$url" >> $GITHUB_OUTPUT
          echo "summary=$sm" >> $GITHUB_OUTPUT
          
          echo "Run link: $url"
          echo "Summary: $sm"
          
      - name: Write pull request comment
        if: env.event == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Run-link: ${{ steps.plan.outputs.run_link }}
            #### Summary: \`${{ steps.plan.outputs.summary }}\``;
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
            })
    
      - name: Terraform Apply
        if: ${{ env.event != 'pull_request' && !startsWith(steps.plan.outputs.summary, 'No changes.') }}
        run: |
          terraform apply plan -no-color > output
          echo "Run link: $(grep '^To view this run in a browser, visit:' -A1 output | grep -v '^To view this run in a browser, visit:' | tr -d '\012\015')"
          echo "Summary: $(grep -E '^(Apply complete!|No changes.)' output | tr -d '\012\015')"